/* Pre-renders the decorative math symbol set to standalone SVG strings.
 *
 * The background layer is the only thing on the site that ever needed MathJax,
 * so rather than shipping a 2MB runtime that lazy-loads webfonts from a CDN, we
 * render the fixed symbol list once here and commit the result as math-symbols.js.
 *
 *   npm install mathjax-full@3
 *   node prerender-symbols.mjs math-symbols.js
 */
import { mathjax } from 'mathjax-full/js/mathjax.js';
import { TeX } from 'mathjax-full/js/input/tex.js';
import { SVG } from 'mathjax-full/js/output/svg.js';
import { liteAdaptor } from 'mathjax-full/js/adaptors/liteAdaptor.js';
import { RegisterHTMLHandler } from 'mathjax-full/js/handlers/html.js';
import { AllPackages } from 'mathjax-full/js/input/tex/AllPackages.js';
import { writeFileSync } from 'node:fs';

const symbols = [
  "\\pi", "e", "i", "\\infty", "\\Sigma", "\\int", "\\sqrt{}",
  "dx", "\\Delta", "\\nabla", "\\alpha", "\\beta", "\\gamma",
  "\\lambda", "\\mu", "\\theta", "\\varphi", "\\psi", "\\emptyset",
  "\\in", "\\Omega", "f(x)", "n!", "x^2", "2\\pi r", "\\pi r^2",
  "a^2+b^2=c^2", "\\lim", "\\log n", "P(A|B)", "\\det(A)",
  "\\oint", "\\bmod p", "C(n,k)", "\\gcd", "\\operatorname{lcm}",
  "\\mathbb{N}", "\\mathbb{Z}", "\\mathbb{Q}", "\\mathbb{R}",
  "\\mathbb{C}", "\\mathbb{P}", "\\mathbb{H}", "\\sigma^2",
  "E[X]", "\\operatorname{Var}(X)", "\\sin^2+\\cos^2=1", "=",
  "\\neq", "\\approx", "\\cong", "\\simeq", "\\leq", "\\geq",
  "\\frac{d}{dx}", "ax^2+bx+c", "y=mx+b", "e^{i\\pi}+1=0",
];

const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);

const doc = mathjax.document('', {
  InputJax: new TeX({ packages: AllPackages }),
  // 'none' inlines every glyph outline, so each SVG stands alone with no shared
  // <defs> and nothing to resolve at runtime. Fill/stroke stay as currentColor,
  // which lets style.css colour the symbols.
  OutputJax: new SVG({ fontCache: 'none' })
});

const out = symbols.map((tex) => adaptor.innerHTML(doc.convert(tex, { display: false })).trim());

const bad = out.filter((s) => !s.startsWith('<svg') || s.includes('data-mjx-error'));
if (bad.length) {
  console.error(`FAILED to render ${bad.length} symbol(s)`);
  process.exit(1);
}

writeFileSync(process.argv[2] ?? 'math-symbols.js',
  '/* Auto-generated by tools/prerender-symbols.mjs — do not hand-edit. */\n' +
  'window.MATH_SYMBOL_SVGS = ' + JSON.stringify(out) + ';\n');

console.log(`wrote ${out.length} symbols`);
